"use client";

import Footer from "@/components/layout/footer";
import Header from "@/components/layout/Header";
import StoreWrapper from "@/providers/StoreWrapper";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import { Suspense } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <StoreWrapper>
          <Suspense fallback={<div>Loading...</div>}>
            <Header />
          </Suspense>
          <main className="">{children}</main>

          <Footer />
        </StoreWrapper>
      </body>
    </html>
  );
}
