"use client";

import ThemeProvider from "@/providers/ThemeProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreWrapper from "@/providers/StoreWrapper";
import Header from "@/components/layout/Header";
import { usePathname } from "next/navigation";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <StoreWrapper>
          <Header />
          <main className="">{children}</main>

          <Footer />
        </StoreWrapper>
      </body>
    </html>
  );
}
