"use client"

import Footer from "@/components/layout/Footer/footer";
import Header1 from "@/components/layout/Header/Header1";
import Header2 from "@/components/layout/Header/Header2";
import Header3 from "@/components/layout/Header/Header3";
import ThemeProvider from "@/providers/ThemeProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreWrapper from "@/providers/StoreWrapper";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <StoreWrapper>
            <Header1 />
            <Header2 />
            <Header3 />
            {children}
            <Footer />
          </StoreWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
